### PR TITLE
Merge #239

### PR DESCRIPTION
**Pull request by rossabaker**
Making sure this still compiles, and making a place to better integrate `serviceF` like @ahjohannessen discussed in #239.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
:+1: Will get to this when fs2/ce3 are on M3 and `UnsafeRunner` is removed.

**Comment by rossabaker** [comment]
Ugh.  It did not compile.  I'm drowning in reviews, so if someone wants to grab this from me, no problem here.  Otherwise, I'll probably get to it this weekend.

**Comment by ahjohannessen** [comment]
@rossabaker Port of #239 is here #250

**Comment by rossabaker** [comment]
Superseded by #250.

**Pull request closed without merging**
