### PR TITLE
Fix gRPC context detachment bug

### PR DESCRIPTION
**Pull request by Tapped**
Fixed by not detaching the context, and instead leak the thread local state. In practice that will not be any issue. 

It's hard to make a regression test, since TestContext (single threaded, controllable threadcontext) doesn't play well with other executor contexts. 

See https://github.com/fiadliel/fs2-grpc/issues/114 for alternative solutions.

### CODE REVIEW

**Comment by rossabaker** [comment]
@ahjohannessen, @frosforever, @jeffersonzapata: do you have any comments on this approach?  I'm not currently using the library in the wild.

**Comment by ahjohannessen** [comment]
Putting this behind an option would be the least intrusive approach.

**Comment by frosforever** [comment]
Sorry, I don't have a view here as I don't use `Context`s.

**Comment by kiril-me** [comment]
GRPC context is a very complicated thing. That doesn't work for us. We have auth interceptors that store the authenticated user in the context, and never get it inside the stream.

**Comment by ahjohannessen** [comment]
Closing this as no progress has happened. Please do not hesitate to reopen if this is relevant now.

**Pull request closed without merging**
