### PR TITLE
updated version of fs2 to 1.0.0

### PR DESCRIPTION
**Pull request by entangled90**

### CODE REVIEW

**Comment by entangled90** [comment]
Can you release a milestone version with fs2_1.0 branch?

**Comment by rossabaker** [comment]
The fs2_1_0 branch hasn't updated the code generator plugin yet.  I think that's the last remaining work before it's usable.  I need it too -- I'm going to try to find time to finish that this week, unless someone beats me to it.

**Comment by ahjohannessen** [comment]
@rossabaker I have opened a PR that has necessary adjustments to the code generator plus updates.

**Comment by rossabaker** [comment]
Superseded by #34.

**Pull request closed without merging**
