### PR TITLE
all: initial setup for Scala 3 support

### PR DESCRIPTION
**Pull request by ahjohannessen**

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@rossabaker `.withDottyCompat` is needed for ScalaPB 0.11.0-M5 as it is not yet published for Scala 3.0.0-RC1.

**Comment by ahjohannessen** [comment]
@rossabaker Probably a good idea to publish a v1.0.0-M2 if you are ok with the ScalaPB `.withDottyCompat` workaround

**Review by rossabaker — APPROVED** [review]
I think `withDottyCompat` is great to start seeing what compiles and what doesn't, but it can lead to unresolvable conflicts downstream.  In other libraries, I've been compiling and testing, but not publishing, under `withDottyCompat`.

Strong :+1: on merging this.  Mild :-1: on releasing it.  It probably won't hurt anyone until scalapb_3 is released, but I've already got a couple scars from `withDottyCompat`.

**Comment by ahjohannessen** [comment]
@rossabaker Agree. Good to get going. ScalaPB is with RC1 is on its way, so I’ll update when it’s on maven

**Pull request merged**
