### PR TITLE
Add context extractor with effect return type

### PR DESCRIPTION
**Pull request by gurinderu**

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@gurinderu Could you please take a look at the [cats-effect-3.0/fs2-3.0 branch](https://github.com/fiadliel/fs2-grpc/pull/237/files#diff-9ee549d25402b05395ac1413d8ddbf440b1a588fab72ef27cadac2d203125fdb) - I think what you are adding is great. `service` could probably be implemented in terms of your `serviceF`.

@gurinderu I have no problem with that this is merged into current series, but I think that your 'serviceF' should be the standard code generated signature in fs2-grpc 1.0.x.

@rossabaker WDYT?

**Comment by gurinderu** [comment]
@ahjohannessen I'll take a look, thanks. I have already implement service through serviceF. Completely agree with you that this method is more general and can be a default, but I didn't touch the service method for backward compatibility.

**Review by rossabaker — APPROVED** [review]
:+1:

**Comment by rossabaker** [comment]
The branch @ahjohannessen referred to is now master.  CE2 development can continue on series/0.x.

**Comment by gurinderu** [comment]
@rossabaker do you have plans to make release for 0.7.x ?

**Comment by rossabaker** [comment]
I can do that.  Do we want to call it 0.7 or bump to 0.8 for the new feature?

**Comment by gurinderu** [comment]
Hm, this is an api change and look like it should be 0.8

**Comment by rossabaker** [comment]
Released as v0.8.0.

**Pull request merged**
