### PR TITLE
Update/compilerplugin 0.11.1

### PR DESCRIPTION
**Pull request by ahjohannessen**

### CODE REVIEW

**Comment by rossabaker** [comment]
Are we going to actively maintain the CE2 release series?

**Comment by ahjohannessen** [comment]
>Are we going to actively maintain the CE2 release series?

Hopefully, we can move off CE2 ASAP, but I suppose not everyone is ready for that? At work we use 0.10.0. What are you thinking?

**Comment by ahjohannessen** [comment]
@rossabaker Can you publish a 1.0.1 version such that dependent libs can build for Scala 3.0.0-RC2? (In similar spirit as CE 3.0.1 / Fs2 3.0.1)

**Comment by rossabaker** [comment]
I mostly just mash merge buttons on this project.  If you're using 0.10.x and would benefit from this, I'm happy to cut a second release.

**Comment by ahjohannessen** [comment]
I would greatly appreciate to get a 1.0.1 and a 0.10.1 release :)

**Comment by ahjohannessen** [comment]
My EventStoreDB library, https://github.com/ahjohannessen/sec, is on 1.0.0 and work apps are on 0.10.x.

**Pull request merged**
