### PR TITLE
all: scalafmtAll

### PR DESCRIPTION
**Pull request by ahjohannessen**

### CODE REVIEW

**Comment by rossabaker** [comment]
:+1: to doing this, but a couple tweaks:

I'm not a fan of vertical alignment.  This leads to bloated diffs.  `align: none` is one of the few non-default settings I tend to apply.

I would also make the format test part of the build, or it'll never stay current with PRs.

**Comment by ahjohannessen** [comment]
I use this in another project:

```
//https://github.com/scalameta/scalafmt/releases
version = "2.3.2"

maxColumn = 120

danglingParentheses = false

align {

  arrowEnumeratorGenerator = true
  ifWhileOpenParen         = false
  openParenCallSite        = true
  openParenDefnSite        = true

  tokens = [
    { code = "=",       owner = "(Enumerator.Val|Term.Assign|Defn.(Va(l|r)|Def|Type))" }
    { code = "<-",      owner = "Enumerator.Generator" }
    { code = "=>",      owner = "Case" }
    { code = "->",      owner = "Term.ApplyInfix" }
    { code = "//",      owner = ".*" }
    { code = "{",       owner = "Template" }
    { code = "}",       owner = "Template" }
    { code = "%",       owner = "Term.ApplyInfix" }
    { code = "%%",      owner = "Term.ApplyInfix" }
    { code = "%%%",     owner = "Term.ApplyInfix" }
    { code = "extends", owner = "Defn.(Class|Trait|Object)" }
  ]

  tokenCategory = {
    "Equals": "Assign"
    "LeftArrow": "Assign"
  }
}

continuationIndent {
  defnSite   = 2
  extendSite = 2
  callSite   = 2
}

newlines {
  penalizeSingleSelectMultiArgList = false
  sometimesBeforeColonInMethodReturnType = false
  avoidAfterYield = false
}

optIn.annotationNewlines = false

rewrite {
  rules = [SortImports, RedundantBraces]
  redundantBraces.maxLines = 1
}

docstrings = JavaDoc

project {
  git = true

  includeFilters = [
    ".*\\.scala$"
  ]

  excludeFilters = [
    ".*\\.sbt$"
  ]
}
```

**Comment by ahjohannessen** [comment]
>I would also make the format test part of the build, or it'll never stay current with PRs.

how should we go about that? :)

**Comment by ahjohannessen** [comment]
@rossabaker changed `align: none` and updated PR

**Comment by ahjohannessen** [comment]
@rossabaker I added the `scalafmtCheckAll` task to travis

**Pull request merged**
